name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build de la imagen del backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: false
          cache-from: type=gha,scope=back
          cache-to: type=gha,mode=max,scope=back

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build de la imagen del frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: false
          cache-from: type=gha,scope=front
          cache-to: type=gha,mode=max,scope=front
